language: java
script: mvn install
jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
- oraclejdk11
- openjdk8
- openjdk9
- openjdk10
- openjdk11

before_deploy:
  # Debug command to explore build directory inside travis
  - ls -l *
  # Store project version for replacement trick
  - mvn help:evaluate -B -Dexpression=project.version 2>/dev/null | grep -v '\[' >version.txt
  - cat version.txt
  # Create deployment package for runnable application
  - mvn -DskipTests=true package
  # Update application version in bintray deployment descriptor file
  - sed -i "s/@VERSION@/$(cat version.txt)/g" descriptor.json

deploy:
  provider: bintray
  file: ./descriptor.json
  skip_cleanup: true
  on: master
  key:
    secure: gjk2oyB3bJBu+lX8yMODThE0iw9Shssuh+AIBfRYiLl/TZPA5NL3nqErCjlnE38c9S1/30JZgKZ/pW3CSAEW0Uwwm7Qa32PhDWgWlMASqB7XUkVh/ELxUwqTfsWHBJJmBaDTd2QtDCbNrHhq+JQBHs9FPW5njjcRoG2WqTumDyugCaCx9zHA40vPKzJM+0JWrx1VP27p32nHHznqx/mgnSuI/iOFctMkALUMBEVwH/r7RQNdR83q6gpXnKT7AN5Z+B5ELDieujCaXNhnswsTvA2SbNupp9U+tRCIJe0AfK8x91IbePLnqDyY5qacp84uABWOguJUMtQJ1b3xAWXBfm6c7/GxqRoan7M3iSXt7ToTK/m1lAkT7yeId14mwJsmBxrAlsinNaGCyUnoUR2+qZi0l2N7BtkXNMa0M9KElvDi/f13f1toxeu2VgrPup7ZEZovcd0iy3zudphKuOOM3xdbo/w1KrhkG3250Znl9yDpW+I42FBFxzEUJM5Blf2ZVdrSJkEQUlptkosqewGVAAgneAmdsjpSaUFlkKwfbT5sXGH39HBFSLNmgQMhNs7rMTLgrKJ3KCMBvhWB299/petCBuyLrYyaV+zTGEcGGTmyhm+sLyLJwGCjKkwnCN/R+EVUDjifJZOUlafdsGQL7lpLg41R4xXYdgGbNoPhHw4=
  user:
    secure: P1NYVaYbXh6LUBpj8sQWGYf/sWvIZiRzCdftfiDmak8rQKat38Hx0ueYUtLYV3vbmMWkZa6fyFuh2aCcVLNSMQEiGP/mLAUkJNAjz16x3LpVwMe+k0ACbQJlp58PQXMynfL9QYQW0WkXU/VHVkjYvsHwqdZQf7ychIYzscQjh5qF6nCHExZ/xs472SY6stp1XQxAEU46cyY+cFxTfs7v8OkVs9DJulriW7FVC/erPcXxget9NvJMyNnAAyUzVVaKXamLcTh9jYT0os778RoHcHi6nznKJOZhsbgQ0+CpuKbBI3jLq/XpJ3hygZ1eo8oyCjkp3zWWCfamcnZbsegMR2B9YTJxICJ59JCU9dlzQervWmn4WpAZS2z9CgyZRkkm2Qw1RkhL/REEmRiFHPYXKBzQA3zMZZLVF82rFod6ZdtApiky/12Plm6M0DXW6jBi1Iq90NaJ7HUeh4X0v433V0Z24lHmIhewVPqY7WSf+hacjpxyO8OS7wfT9eXt15nPhJJ2Ea7c+1loYzN+mxKDL9Jq5/m5/f365+oGKEDVuuUmcPvl6OB+37DuEPytjpBvM7kXcpvqx0OHZI7nxtQ2VHGA1AJ2ZsE7iI3/phIjiMkAUGHJ8JKVMh/QzQCcjh99uTMT0b34EVtsktJ5wLpfIa4pKZVhkotepoxgXge6U/k=
